modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0-only"

[[mods]]
modId="colorchallenge"
version="${version}"
displayName="Color Challenge"
description='''Compete to earn 10,000 gold by mining and selling ores!'''
authors="ksoichiro"
displayURL="https://github.com/ksoichiro/ColorChallenge"

[[dependencies.colorchallenge]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.colorchallenge]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.colorchallenge]]
modId="architectury"
mandatory=true
versionRange="[9,)"
ordering="AFTER"
side="BOTH"
