modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL-3.0-only"

[[mods]]
modId = "colorchallenge"
version = "${version}"
displayName = "Color Challenge"
description = '''Compete to earn 10,000 gold by mining and selling ores!'''
authors = "ksoichiro"
displayURL = "https://github.com/ksoichiro/ColorChallenge"

[[dependencies.colorchallenge]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.colorchallenge]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,1.21.6)"
ordering = "NONE"
side = "BOTH"

[[dependencies.colorchallenge]]
modId = "architectury"
type = "required"
versionRange = "[16,)"
ordering = "AFTER"
side = "BOTH"
